### ISSUE TITLE
how to know if the response comes from the cache ?

### ISSUE THREAD

**Issue by svengau** [Goldziher/axios-simple-cache-adapter#8]
thanks for this really simple library, and easy to configure. 

Other libs provide an extra parameter on the response (e.g response.request.fromCache, or response.cached) to indicate if the reponse comes from the cache or not. How is it possible to know it with axios-simple-cache-adapter ?

**Comment by Goldziher** [comment]
> thanks for this really simple library, and easy to configure. 
> 
> Other libs provide an extra parameter on the response (e.g response.request.fromCache, or response.cached) to indicate if the reponse comes from the cache or not. How is it possible to know it with axios-simple-cache-adapter ? 

Hi there. Currently the only way to know is to run i debug=true, and see the log out. 

Is this runtime behaviour you are looking for, or for dev only?

**Comment by svengau** [comment]
It's handy to have this information, even in production.

**Comment by Goldziher** [comment]
> It's handy to have this information, even in production.

Ok, PR welcome
